"""Dormant CRCON anti-corruption foundation for future endpoint migrations."""

from .api import CrconApiClient
from .cache import TtlCache
from .dto import (
    CRCON_MAP_HISTORY_DEFAULT_MAX_ENTRIES,
    CrconApiDocumentation,
    CrconEncounter,
    CrconEndpointDocumentation,
    CrconHistoricalMap,
    CrconLiveGameStats,
    CrconLivePlayer,
    CrconLiveScoreboard,
    CrconMapHistory,
    CrconMapPage,
    CrconMapScoreboard,
    CrconPreviousMap,
    CrconPlayerHistoryEntry,
    CrconPlayerHistoryPage,
    CrconPublicInfo,
)
from .models import (
    CRCON_CONTRACT_REVISION,
    CRCON_REFERENCE_BRANCH,
    CRCON_REPOSITORY,
    CRCON_TARGET_VERSION,
    CrconApiError,
    CrconApiAuthenticationError,
    CrconCapability,
    CrconCapabilityReport,
    CrconCapabilityResult,
    CrconCapabilityStatus,
    CrconAggregateState,
    CrconPlayerHistoryState,
    CrconContractStatus,
    CrconDatabaseError,
    CrconError,
    CrconSchemaIncompatibleError,
    CrconSourceMetadata,
    CrconUnavailableError,
)
from .postgres_repository import PostgresCrconRepository
from .repository import (
    CrconCurrentMap,
    CrconMatchCombatStats,
    CrconMatchLogEvent,
    CrconPlayerAggregate,
    CrconPlayerProfileAggregate,
    CrconRankingRow,
    CrconReadRepository,
    CrconServerAggregate,
    CrconServerScope,
    resolve_server_scope,
)

__all__ = [
    "CRCON_CONTRACT_REVISION",
    "CRCON_MAP_HISTORY_DEFAULT_MAX_ENTRIES",
    "CRCON_REFERENCE_BRANCH",
    "CRCON_REPOSITORY",
    "CRCON_TARGET_VERSION",
    "CrconApiClient",
    "CrconAggregateState",
    "CrconApiAuthenticationError",
    "CrconApiDocumentation",
    "CrconApiError",
    "CrconCapability",
    "CrconCapabilityReport",
    "CrconCapabilityResult",
    "CrconCapabilityStatus",
    "CrconContractStatus",
    "CrconDatabaseError",
    "CrconEncounter",
    "CrconEndpointDocumentation",
    "CrconCurrentMap",
    "CrconError",
    "CrconSchemaIncompatibleError",
    "CrconSourceMetadata",
    "CrconMatchCombatStats",
    "CrconMatchLogEvent",
    "CrconHistoricalMap",
    "CrconLiveGameStats",
    "CrconLivePlayer",
    "CrconLiveScoreboard",
    "CrconMapHistory",
    "CrconMapPage",
    "CrconMapScoreboard",
    "CrconPlayerAggregate",
    "CrconPlayerHistoryEntry",
    "CrconPlayerHistoryPage",
    "CrconPlayerHistoryState",
    "CrconPlayerProfileAggregate",
    "CrconPreviousMap",
    "CrconPublicInfo",
    "CrconReadRepository",
    "CrconRankingRow",
    "CrconServerAggregate",
    "CrconServerScope",
    "CrconUnavailableError",
    "PostgresCrconRepository",
    "TtlCache",
    "resolve_server_scope",
]
