"""Sanitized, injectable HTTP client for the verified CRCON foundation API."""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen

from .dto import (
    CrconApiDocumentation,
    CrconLiveGameStats,
    CrconLiveScoreboard,
    CrconMapHistory,
    CrconMapPage,
    CrconMapScoreboard,
    CrconPreviousMap,
    CrconPlayerHistoryPage,
    CrconPublicInfo,
    parse_api_documentation,
    parse_live_game_stats,
    parse_live_scoreboard,
    parse_map_history,
    parse_map_scoreboard,
    parse_previous_map,
    parse_players_history,
    parse_public_info,
    parse_scoreboard_maps,
)
from .models import CrconApiAuthenticationError, CrconApiError


VERSION_ENDPOINT = "/api/get_version"
API_DOCUMENTATION_ENDPOINT = "/api/get_api_documentation"
PUBLIC_INFO_ENDPOINT = "/api/get_public_info"
LIVE_GAME_STATS_ENDPOINT = "/api/get_live_game_stats"
LIVE_SCOREBOARD_ENDPOINT = "/api/get_live_scoreboard"
SCOREBOARD_MAPS_ENDPOINT = "/api/get_scoreboard_maps"
MAP_SCOREBOARD_ENDPOINT = "/api/get_map_scoreboard"
MAP_HISTORY_ENDPOINT = "/api/get_map_history"
PREVIOUS_MAP_ENDPOINT = "/api/get_previous_map"
PLAYERS_HISTORY_ENDPOINT = "/api/get_players_history"
USER_AGENT = "HLL-Vietnam-CRCON-BFF/0.1"

Transport = Callable[[Request, float], Any]


class CrconApiClient:
    """Minimal CRCON GET client whose transport and auth headers are injectable."""

    def __init__(
        self,
        *,
        base_url: str,
        timeout_seconds: float,
        retries: int = 0,
        headers: Mapping[str, str] | None = None,
        transport: Transport | None = None,
    ) -> None:
        self._base_url = _validate_base_url(base_url)
        if timeout_seconds <= 0:
            raise ValueError("timeout_seconds must be positive.")
        if retries not in {0, 1}:
            raise ValueError("retries must be zero or one.")
        self._timeout_seconds = timeout_seconds
        self._retries = retries
        self._headers = {
            **dict(headers or {}),
            "Accept": "application/json",
            "User-Agent": USER_AGENT,
        }
        self._transport = transport or _open_request

    def get_version(self) -> str:
        """Return the normalized deployed CRCON version string."""
        result = self._get_result(VERSION_ENDPOINT)
        if not isinstance(result, str):
            raise CrconApiError("CRCON API returned an unexpected version response.")
        normalized = result.strip()
        if normalized.lower().startswith("v"):
            normalized = normalized[1:]
        if not normalized:
            raise CrconApiError("CRCON API returned an unexpected version response.")
        return normalized

    def get_api_documentation(self) -> CrconApiDocumentation:
        """Return sanitized endpoint metadata generated by CRCON introspection."""
        return parse_api_documentation(self._get_result(API_DOCUMENTATION_ENDPOINT))

    def get_public_info(self) -> CrconPublicInfo:
        return parse_public_info(self._get_dict(PUBLIC_INFO_ENDPOINT))

    def get_live_game_stats(self) -> CrconLiveGameStats:
        """Return match-scoped stats under the verified HLL 12.0.1 contract."""
        return parse_live_game_stats(self._get_dict(LIVE_GAME_STATS_ENDPOINT))

    def get_live_scoreboard(self) -> CrconLiveScoreboard:
        return parse_live_scoreboard(self._get_dict(LIVE_SCOREBOARD_ENDPOINT))

    def get_scoreboard_maps(
        self,
        *,
        page: int = 1,
        limit: int = 100,
        server_number: int | str | None = None,
    ) -> CrconMapPage:
        query: dict[str, object] = {"page": page, "limit": limit}
        if server_number is not None:
            query["server_number"] = server_number
        return parse_scoreboard_maps(self._get_dict(SCOREBOARD_MAPS_ENDPOINT, query))

    def get_map_scoreboard(self, *, map_id: int | str) -> CrconMapScoreboard:
        return parse_map_scoreboard(
            self._get_dict(MAP_SCOREBOARD_ENDPOINT, {"map_id": map_id})
        )

    def get_map_history(
        self,
        *,
        pretty: bool = False,
    ) -> CrconMapHistory:
        query = {"pretty": "true"} if pretty else None
        return parse_map_history(self._get_result(MAP_HISTORY_ENDPOINT, query))

    def get_previous_map(self) -> CrconPreviousMap:
        result = self._get_result(PREVIOUS_MAP_ENDPOINT)
        if result is not None and not isinstance(result, dict):
            raise CrconApiError("CRCON API returned an unexpected response.")
        return parse_previous_map(result)

    def get_players_history(
        self,
        *,
        player_name: str | None = None,
        player_id: str | None = None,
        page: int = 1,
        page_size: int = 10,
        exact_name_match: bool = False,
    ) -> CrconPlayerHistoryPage:
        """Read the bounded, authenticated v12.0.1 player-history endpoint."""
        if isinstance(page, bool) or page < 1:
            raise ValueError("CRCON player-history page must be positive.")
        if isinstance(page_size, bool) or page_size < 1 or page_size > 100:
            raise ValueError("CRCON player-history page_size must be between 1 and 100.")
        normalized_name = str(player_name or "").strip()
        normalized_id = str(player_id or "").strip()
        if bool(normalized_name) == bool(normalized_id):
            raise ValueError(
                "CRCON player-history requires exactly one safe identity filter."
            )
        query: dict[str, object] = {"page": page, "page_size": page_size}
        if normalized_name:
            query["player_name"] = normalized_name
            query["exact_name_match"] = "true" if exact_name_match else "false"
        else:
            query["player_id"] = normalized_id
        try:
            return parse_players_history(
                self._get_dict(PLAYERS_HISTORY_ENDPOINT, query)
            )
        except ValueError:
            raise CrconApiError(
                "CRCON API returned an unexpected player-history response."
            ) from None

    def _get_dict(
        self,
        endpoint: str,
        query: Mapping[str, object] | None = None,
    ) -> dict[str, object]:
        result = self._get_result(endpoint, query)
        if not isinstance(result, dict):
            raise CrconApiError("CRCON API returned an unexpected response.")
        return result

    def _get_result(
        self,
        endpoint: str,
        query: Mapping[str, object] | None = None,
    ) -> object:
        url = _join_url(self._base_url, endpoint, query)
        for _attempt in range(self._retries + 1):
            request = Request(url, headers=self._headers, method="GET")
            try:
                with self._transport(request, self._timeout_seconds) as response:
                    payload = json.loads(response.read().decode("utf-8"))
                return _unwrap_result(payload)
            except CrconApiError:
                raise
            except HTTPError as error:
                if error.code in {401, 403}:
                    raise CrconApiAuthenticationError(
                        "CRCON API authentication or permission was rejected."
                    ) from None
                continue
            except (
                URLError,
                TimeoutError,
                OSError,
                UnicodeError,
                json.JSONDecodeError,
            ):
                continue

        raise CrconApiError("CRCON API request failed.") from None


def _validate_base_url(base_url: str) -> str:
    normalized = str(base_url or "").strip().rstrip("/")
    parsed = urlsplit(normalized)
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError("CRCON API base URL must be an unauthenticated HTTP(S) origin.")
    return normalized


def _join_url(
    base_url: str,
    endpoint: str,
    query: Mapping[str, object] | None,
) -> str:
    if not endpoint.startswith("/api/") or ".." in endpoint:
        raise ValueError("CRCON API endpoint is invalid.")
    parsed = urlsplit(base_url)
    base_path = parsed.path.rstrip("/")
    path = f"{base_path}{endpoint}"
    query_string = urlencode(query or {})
    return urlunsplit((parsed.scheme, parsed.netloc, path, query_string, ""))


def _unwrap_result(payload: object) -> object:
    if not isinstance(payload, dict):
        return payload
    if payload.get("failed") is True:
        raise CrconApiError("CRCON API reported a failed response.")
    return payload.get("result") if "result" in payload else payload


def _open_request(request: Request, timeout_seconds: float) -> Any:
    return urlopen(request, timeout=timeout_seconds)
